Config = {}

Config.AuthorizedWeapons = {
    recruit = { -- Alumno
        {weapon = 'WEAPON_COMBATPISTOL', price = 1000},
        {weapon = 'WEAPON_BZGAS', price = 100},
        {weapon = 'WEAPON_STUNGUN', price = 0},
        {weapon = 'WEAPON_NIGHTSTICK', price = 0},
        {weapon = 'WEAPON_FLASHLIGHT', price = 0}
    },

    officer = { -- Oficial
        {weapon = 'WEAPON_PUMPSHOTGUN', = price = 5000},
        {weapon = 'WEAPON_SMG', price = 3000},
        {weapon = 'WEAPON_COMBATPISTOL', price = 1000},
        {weapon = 'WEAPON_BZGAS', price = 100},
        {weapon = 'WEAPON_STUNGUN', price = 0},
        {weapon = 'WEAPON_NIGHTSTICK', price = 0},
        {weapon = 'WEAPON_FLASHLIGHT', price = 0}
    },

    sergeant = { -- Oficial II
        {weapon = 'WEAPON_CARBINERIFLE', price = 7000},
        {weapon = 'WEAPON_SPECIALCARBINE', price = 6500},
        {weapon = 'WEAPON_ASSAULTSHOTGUN', price = 6000},
        {weapon = 'WEAPON_PUMPSHOTGUN',  price = 5000},
        {weapon = 'WEAPON_ASSAULTSMG', price = 4000},
        {weapon = 'WEAPON_SMG', price = 3000},
        {weapon = 'WEAPON_COMBATPISTOL', price = 1000},
        {weapon = 'WEAPON_BZGAS', price = 100},
        {weapon = 'WEAPON_STUNGUN', price = 0},
        {weapon = 'WEAPON_NIGHTSTICK', price = 0},
        {weapon = 'WEAPON_FLASHLIGHT', price = 0}
    },
    sergeant_chief = { -- Sheriff
        {weapon = 'WEAPON_MARKSMANRIFLE', price = 6000 },
        {weapon = 'WEAPON_MUSKET', price = 4000},
        {weapon = 'WEAPON_DOUBLEBARRELSHOTGUN', price = 3000},
        {weapon = 'WEAPON_REVOLVER', price = 1000},
        {weapon = 'WEAPON_COMBATPISTOL', price = 1000},
        {weapon = 'WEAPON_MACHETE', price = 1000},
        {weapon = 'WEAPON_SWITCHBLADE', price = 1000},
        {weapon = 'WEAPON_BZGAS', price = 100},
        {weapon = 'WEAPON_STUNGUN', price = 0},
        {weapon = 'WEAPON_NIGHTSTICK', price = 0},
        {weapon = 'WEAPON_FLASHLIGHT', price = 0}
    },
    intendent = { -- Inspector
        {weapon = 'WEAPON_SNIPERRIFLE', price = 10000},
        {weapon = 'WEAPON_CARBINERIFLE', price = 7000},
        {weapon = 'WEAPON_SPECIALCARBINE', price = 6500},
        {weapon = 'WEAPON_ASSAULTSHOTGUN', price = 6000},
        {weapon = 'WEAPON_PUMPSHOTGUN',  price = 5000},
        {weapon = 'WEAPON_ASSAULTSMG', price = 4000},
        {weapon = 'WEAPON_SMG', price = 3000},
        {weapon = 'WEAPON_FLAREGUN', price = 3000},
        {weapon = 'WEAPON_APPISTOL', price = 2000},
        {weapon = 'WEAPON_COMBATPISTOL', price = 1000},
        {weapon = 'WEAPON_BZGAS', price = 100},
        {weapon = 'WEAPON_SMOKEGRENADE', price = 100},
        {weapon = 'WEAPON_STUNGUN', price = 0},
        {weapon = 'WEAPON_NIGHTSTICK', price = 0},
        {weapon = 'WEAPON_FLASHLIGHT', price = 0}
    },
    lieutenant = { -- Detective
        {weapon = 'WEAPON_SNIPERRIFLE', price = 5000},
        {weapon = 'WEAPON_SAWNOFFSHOTGUN', price = 4000},
        {weapon = 'WEAPON_FLAREGUN', price = 3000},
        {weapon = 'WEAPON_APPISTOL', price = 2000},
        {weapon = 'WEAPON_COMBATPISTOL', price = 1000},
        {weapon = 'WEAPON_BZGAS', price = 100},
        {weapon = 'WEAPON_SMOKEGRENADE', price = 100},
        {weapon = 'WEAPON_STUNGUN', price = 0},
        {weapon = 'WEAPON_NIGHTSTICK', price = 0},
        {weapon = 'WEAPON_FLASHLIGHT', price = 0}
    },
    chef = { -- Comisario
        {weapon = 'WEAPON_HEAVYRIFLE', price = 25000},
        {weapon = 'WEAPON_COMBATMG', price = 20000},
        {weapon = 'WEAPON_MG', price = 15000},
        {weapon = 'WEAPON_SNIPERRIFLE', price = 10000},
        {weapon = 'WEAPON_CARBINERIFLE', price = 7000},
        {weapon = 'WEAPON_SPECIALCARBINE', price = 6500},
        {weapon = 'WEAPON_ASSAULTSHOTGUN', price = 6000},
        {weapon = 'WEAPON_PUMPSHOTGUN',  price = 5000},
        {weapon = 'WEAPON_GUSENBERG', price = 5000},
        {weapon = 'WEAPON_ASSAULTSMG', price = 4000},
        {weapon = 'WEAPON_COMBATPDW', price = 4000},
        {weapon = 'WEAPON_SMG', price = 3000},
        {weapon = 'WEAPON_FLAREGUN', price = 3000},
        {weapon = 'WEAPON_APPISTOL', price = 2000},
        {weapon = 'WEAPON_COMBATPISTOL', price = 1000},
        {weapon = 'WEAPON_MARKSMANPISTOL', price = 1000},
        {weapon = 'WEAPON_BZGAS', price = 100},
        {weapon = 'WEAPON_SMOKEGRENADE', price = 100},
        {weapon = 'WEAPON_STUNGUN', price = 0},
        {weapon = 'WEAPON_WRENCH', price = 0},
        {weapon = 'WEAPON_DAGGER', price = 0},
        {weapon = 'WEAPON_NIGHTSTICK', price = 0},
        {weapon = 'WEAPON_FLASHLIGHT', price = 0}
    },

    boss = { -- Super Intendente
        {weapon = 'WEAPON_HEAVYRIFLE', price = 25000},
        {weapon = 'WEAPON_COMBATMG', price = 20000},
        {weapon = 'WEAPON_MG', price = 15000},
        {weapon = 'WEAPON_SNIPERRIFLE', price = 10000},
        {weapon = 'WEAPON_CARBINERIFLE', price = 7000},
        {weapon = 'WEAPON_SPECIALCARBINE', price = 6500},
        {weapon = 'WEAPON_ASSAULTSHOTGUN', price = 6000},
        {weapon = 'WEAPON_PUMPSHOTGUN',  price = 5000},
        {weapon = 'WEAPON_GUSENBERG', price = 5000},
        {weapon = 'WEAPON_ASSAULTSMG', price = 4000},
        {weapon = 'WEAPON_COMBATPDW', price = 4000},
        {weapon = 'WEAPON_SMG', price = 3000},
        {weapon = 'WEAPON_FLAREGUN', price = 3000},
        {weapon = 'WEAPON_APPISTOL', price = 2000},
        {weapon = 'WEAPON_COMBATPISTOL', price = 1000},
        {weapon = 'WEAPON_MARKSMANPISTOL', price = 1000},
        {weapon = 'WEAPON_BZGAS', price = 100},
        {weapon = 'WEAPON_SMOKEGRENADE', price = 100},
        {weapon = 'WEAPON_STUNGUN', price = 0},
        {weapon = 'WEAPON_WRENCH', price = 0},
        {weapon = 'WEAPON_DAGGER', price = 0},
        {weapon = 'WEAPON_NIGHTSTICK', price = 0},
        {weapon = 'WEAPON_FLASHLIGHT', price = 0}
    }
}